In [15]:
import numpy as np
a=np.array([1, 2, 3, 4])

In [16]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a, b)
toc=time.time()

print(c)
print("vectorized version:"+ str(1000*(toc-tic))+"ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()

print(c)
print("For loop:"+str(1000*(toc-tic))+"ms")

249542.06536873567
vectorized version:1.230001449584961ms
249542.06536873183
For loop:522.7468013763428ms


In [17]:
a= np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(a)            

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [18]:
cal=a.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [19]:
per= 100*a/cal.reshape(1,4)

In [20]:
print(per)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [21]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [23]:
c.shape

(12288, 45)

In [28]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [29]:
c.shape

(2, 3)

In [31]:
print(a)
print(b)
print(c)

[[-0.05882973 -0.40622677  0.09100047]
 [-0.60017943 -0.50184177 -0.44828926]]
[[0.98492398]
 [0.44567897]]
[[ 0.92609425  0.57869721  1.07592445]
 [-0.15450046 -0.0561628  -0.0026103 ]]


In [32]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [33]:
c.shape

(3, 3)

In [34]:
print(a)
print(b)
print(c)

[[ 1.7291149   1.76093033 -0.04716554]
 [-0.49821633  1.26592926  0.29308337]
 [-0.13242698 -1.13199758 -0.05081816]]
[[ 0.09104191]
 [ 0.73882413]
 [-0.99989349]]
[[ 0.15742192  0.16031845 -0.00429404]
 [-0.36809425  0.93529908  0.21653707]
 [ 0.13241287  1.13187702  0.05081275]]


In [27]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
#c = a*b